[2023-08-18 19:57:59,819] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Products_ETL.get_number_pages manual__2023-08-18T19:57:57.283364+00:00 [queued]>
[2023-08-18 19:57:59,825] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Products_ETL.get_number_pages manual__2023-08-18T19:57:57.283364+00:00 [queued]>
[2023-08-18 19:57:59,825] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-18 19:57:59,826] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-08-18 19:57:59,826] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-18 19:57:59,835] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_number_pages> on 2023-08-18 19:57:57.283364+00:00
[2023-08-18 19:57:59,844] {standard_task_runner.py:52} INFO - Started process 7432 to run task
[2023-08-18 19:57:59,848] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Products_ETL', 'get_number_pages', 'manual__2023-08-18T19:57:57.283364+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpnz7e101n', '--error-file', '/tmp/tmpwop4urpx']
[2023-08-18 19:57:59,850] {standard_task_runner.py:80} INFO - Job 4: Subtask get_number_pages
[2023-08-18 19:57:59,939] {task_command.py:371} INFO - Running <TaskInstance: Products_ETL.get_number_pages manual__2023-08-18T19:57:57.283364+00:00 [running]> on host 0110d0e687e9
[2023-08-18 19:58:00,027] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-08-18 19:58:00,092] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sol
AIRFLOW_CTX_DAG_ID=Products_ETL
AIRFLOW_CTX_TASK_ID=get_number_pages
AIRFLOW_CTX_EXECUTION_DATE=2023-08-18T19:57:57.283364+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-18T19:57:57.283364+00:00
[2023-08-18 19:58:00,094] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: getNumberPageProducts() takes 0 positional arguments but 1 was given
[2023-08-18 19:58:00,115] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=Products_ETL, task_id=get_number_pages, execution_date=20230818T195757, start_date=20230818T195759, end_date=20230818T195800
[2023-08-18 19:58:00,140] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task get_number_pages (getNumberPageProducts() takes 0 positional arguments but 1 was given; 7432)
[2023-08-18 19:58:00,183] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-08-18 19:58:00,227] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
